spring.application.name=quado
server.port=3000

# Thư mục lưu dữ liệu ArcadeDB (Embedded Graph Database)
arcadedb.path=./arcadedb_graph

spring.ai.mcp.server.name=quado
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.instructions=Native MCP server for code indexing and graph queries.

spring.ai.mcp.server.annotation-scanner.enabled=true

spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false

spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

spring.main.banner-mode=off
logging.level.vn.cxn.graph=INFO

# Cấu hình ghi log ra file
logging.file.name=app_logs/log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Cấu hình Spring AI Ollama
spring.ai.ollama.base-url=https://ollama-api.cxn.vn
spring.ai.ollama.chat.options.model=qwen3-coder:480b-cloud
spring.ai.ollama.chat.options.temperature=0.2

# Cấu hình luồng chạy song song cho phân tích AI
quado.ai.parallel-threads=3
